version: '3.4'

services:
  roulettecore:
    image: ${DOCKER_REGISTRY-}roulettecore
    build:
      context: .
      dockerfile: RouletteCore/Dockerfile
    depends_on:
            - db
  db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"